### ISSUE TITLE
Task Cards

### ISSUE THREAD

**Issue by craigbutcher** [pa11y/pa11y-dashboard#102]
Hi,

It would be great if there was a way to drag and drop cards around and/or arrange by date/errors?

Thanks!

**Comment by rowanmanning** [comment]
Hey @legobot, due to the project split with the dashboard and webservice this is way more difficult to do than it should be :(

We'd accept a PR adding this, but it'd have to appear as something like an "index" field in the webservice database and then the dashboard would have to do a load of fiddling around with the API. If anyone's interested then please discuss beforehand – these kinds of features that require updates to three different repos can be tricky.

**Comment by rowanmanning** [comment]
Going to close this as we're not prioritising feature work in Dashboard. If somebody finds this and does the work, we'll still accept a PR.
