### ISSUE TITLE
Long names of pages get truncated on the dashboard

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y-dashboard#106]
On the dashboard, the name of each page being tested has a limited space for display, this means that names that are more than 25 chars or so get truncated. There's no apparent way of accessing the full name unless clicking and going to the results page.

This makes almost impossible to distinguish some pages with very similar names, as shown here:

![screen shot 2016-04-20 at 11 28 44](https://cloud.githubusercontent.com/assets/1792637/14671690/17dbcb1c-06eb-11e6-974a-b171e995f956.png)

Possible alternatives:
- Making the font smaller
- Adding a second line of text for the title, if necessary
- Adding (Changing) the tooltip so the full name is displayed on mouse over

**Comment by frvge** [comment]
The current master already contains the full URL on hover (on Chrome) because of the title attribute. @joseluisbolos .

**Comment by josebolos** [comment]
@frvge Sorry I missed this! Indeed, it shows the URLs. When I created the issue I was thinking about the name of each page though. I've created #165 in order to study further changes to the view that would help fix this problem.

**Comment by adamki** [comment]
I wanted to ask what the status of this issue is. It seems that the display issue solution is still up in the air/not settled? Am I correct in assuming that the display issue will be address in [#165](https://github.com/pa11y/dashboard/issues/165)?

If there are minor tweaks to be made here, I would really love to chat about contributing! Thanks in advance.

**Comment by hollsk** [comment]
Hey @adamki - we'd love to have you contribute! You're right, our current thinking is that the solution proposed in #165 would be the best approach. It turned out to be really difficult to work something out with the current tile format, so we'd like to change direction. 

There are quite a lot of suggestions in the proposed solution, including filtering and sorting, but we'd accept a pull request that does only some of it - we can iterate on it later. The minimum useful pull request would include CSS to create the list version of the tiles, and a button (or something) somewhere on the page that lets people switch between the tile and list views by setting a cookie. I think we wanted to default to the list view. 

Does it sound like something you'd be interested in?

**Comment by adamki** [comment]
@hollsk Yep, I'd be happy to take a look!

**Comment by josebolos** [comment]
Fixed by #279.
