### ISSUE TITLE
500  when running the dashboard

### ISSUE THREAD

**Issue by epiespen** [pa11y/pa11y-dashboard#111]
Eeek! 500 error. This is serious.
There isn't much you can do about this.

Error: connect EADDRNOTAVAIL 0.0.0.0:3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1061:14)

Running on Windows 10. 
Node: 4.4.3

**Comment by hollsk** [comment]
Hi @epiespen,

The dashboard isn't able to connect to 0.0.0.0:3000 because some other service is listening on the port. Manually running pa11y-webservice can cause this error, so if you've started up the webservice separately, then please exit it before running pa11y-dashboard again. 

If you're not running pa11y-webservice manually, then something else is listening on the port. You can try to find it by running `netstat -aon | more` from the Windows console and looking for 0.0.0.0:3000 in the local address list - check the number in the PID column against the PIDs in Windows Task Manager to find the culprit. You can either kill that service if it's not important, or configure pa11y to use a different port number. 

Let me know how you get on!

**Comment by epiespen** [comment]
Hi, thanks for your reply @hollsk 

I'm a bit of a newbie on this. My mongodb wasn't running properly, so my service failed and returned the 500 to the dashboard. Works now :) thanks again!

**Comment by hollsk** [comment]
That was also one of the potential problems we considered! We'll update the docs to cover this as it's caught a few people out - glad you got it working. Happy a11ying :-)
