### ISSUE TITLE
How to add new task options (e.g. wait)

### ISSUE THREAD

**Issue by Rayraegah** [pa11y/pa11y-dashboard#127]
![image](https://cloud.githubusercontent.com/assets/1559650/15429117/1d3cb7ba-1e97-11e6-94ce-4f14d8698ccd.png)

I've forked and heavily modified the dashboard for local use, the web app I'm testing has a lot of web components and async html injections.

On an average it takes about 5 seconds for the complete DOM tree to be built after several ajax calls (the dom.ready event is fired at 1.2 seconds).

 I want tests to have a configurable delay option like in the screenshot or a method to use `pa11y --wait 10000` or even `beforeScript` while running pa11y from the dashboard button.

p.s. ignore the typos in the screenshot <3

**Comment by josebolos** [comment]
Hi @Rayraegah

Let me just clarify: you’d like to make the `wait` option accessible via the dashboard?

This is possible, but you’ll need to make a change to pa11y-webservice first. If you’re interested in doing this work yourself then we’d be happy to accept a PR, otherwise we can keep this open as a feature request and one of us can look into it in the future.

Thanks for using pa11y!

**Comment by Rayraegah** [comment]
![image](https://cloud.githubusercontent.com/assets/1559650/15430424/3d1d451c-1e9d-11e6-88b6-65f8f3ac0a1b.png)

I've done this just a minute before you posted the reply. I'll make a pull request on pa11y-webservice and on pa11y-dashboard later today :)

**Comment by Rayraegah** [comment]
The pull request for pa11y-dashboard will throw CI errors, until the web service changes are merged and published :)

**Comment by rowanmanning** [comment]
Oh, this made it into version `1.11.0`. I forgot to close
