### ISSUE TITLE
Could not connect to pa11y-webservice

### ISSUE THREAD

**Issue by syndy1989** [pa11y/pa11y-dashboard#180]
Hi,
I'm new to pa11y and i wanted to check multiple URL's using pa11y-webservice.

OS nam: Windows
Node.js version:4.6.0
pa11y-dashboard version:1.5.0
mongo db version:3.4

i followed the instructions on https://github.com/pa11y/webservice#setup but i'm not quite sure how to setup the environment variables and modify the config files to make it work.
Any advise would be helpful.Thanks in advance

**Comment by josebolos** [comment]
Hi @syndy1989 

Thanks for creating this issue.

Is there any particular reason why you are using pa11y-dashboard `1.5.0`? The latest pa11y-dashboard version is `2.2.1`. `1.5.0` is both ancient, and [unsupported since last December](https://github.com/pa11y/dashboard#support-and-migration).

If you're going to use pa11y-dashboard there's no need to configure pa11y-webservice manually. Configuring pa11y-dashboard will take care of everything. The documentation should probably explain this more clearly, I've just created an issue now in order to address this: #181 

Assuming you already have a MongoDB database set up properly, what I would suggest you to try is:
1. Download the latest version of pa11y-dashboard.
2. Copy one of the sample config files in [https://github.com/pa11y/dashboard/blob/master/config](https://github.com/pa11y/dashboard/blob/master/config) to [create your config file](https://github.com/pa11y/dashboard#option-2-using-config-files), e.g. [development.sample.json](https://github.com/pa11y/dashboard/blob/master/config/development.sample.json).
3. Replace the variables in the file with the correct values for your Mongo installation. You can find a description of the variable in the [webservice README](https://github.com/pa11y/webservice#configurations).
4. Run pa11y-dashboard with:
```bash
NODE_ENV=development node index.js
```
Make sure NODE_ENV is set up to the same value as the config file that you have created before.

That should be it. Please let us know if you have any further problems. Feel free to post your config so far if you're unsure of how to make it work.
