### ISSUE TITLE
How to Setup and run custom Scripts, while using Pa11y Dash

### ISSUE THREAD

**Issue by Zoheb-hassan** [pa11y/pa11y-dashboard#187]
How do i go about running a bunch of scripts like say capture the screenshot, alter the View Port of PhantomJs Browser or add a set of ignore rules globally while running tests, i am aware of how this can be done when using Pa11y CLI but not sure how the script can be initiated while using Pa11y-Dashboard

**Comment by rowanmanning** [comment]
Hi @Zoheb-hassan, currently Pa11y dashboard [does support actions](https://github.com/pa11y/pa11y#actions) which allows you to do _some_ things.

Ignore rules are supported in the task editing, but on a per-task basis rather than globally. You could probably speed up this process manually in the database but it's risky.

The viewport cannot currently be set, and while we don't have the capacity to do this we would be willing to accept a PR adding it. It's not possible to change the viewport mid-way through a test though.

Screenshots are not available in dashboard, and are unlikely to ever be I'm afraid.

Hope this helps
