### ISSUE TITLE
Possible reasons for fluctuating results?

### ISSUE THREAD

**Issue by jlsorak** [pa11y/pa11y-dashboard#215]
I'm testing quite a few of our pages using the dashboard, and the results for these tend to fluctuate a lot. Our sites aren't changing enough to justify this fluctuation, especially as a lot of the pages are static. 

Do you know what may be causing this, should I be setting a larger timeout for the pages (currently using 30000)? Please could you also explain what the timeout does as I don't quite understand what this does. 

Thanks in advance.

![screen shot 2018-09-07 at 13 37 03](https://user-images.githubusercontent.com/25332734/45219622-6e9d0e00-b2a3-11e8-8267-4ebfe376715a.png)

**Comment by hollsk** [comment]
Hi @jlsorak - thanks for using Pa11y!

`timeout` is the length of time that Pa11y will wait for a slow page to load before giving up. I don't know enough about your site to be able to tell you if this will solve your problem.

Can you see a pattern in the reports for the error fluctuations? Are there specific elements that seem to be persistently failing to load, or especially changeable?

**Comment by josebolos** [comment]
Hi @jlsorak!

Did you manage to find out what's going on? In addition to what @hollsk said, I would expect such a huge variation only when there's something on the page that is changing for every page load. In my experience, advertising tends to be the usual culprit, but any kind of 3rd party widget could be responsible for it.

In order to make sure this is the case, you could use the `--screen-capture` flag or [`screenCapture` option](https://github.com/pa11y/pa11y#screencapture-string) and compare the output for the differing test runs.

For anyone having this same issue, we wrote about it on our [troubleshooting guide](https://github.com/pa11y/pa11y/blob/master/TROUBLESHOOTING.md#why-does-pa11y-give-different-results-each-time-it-runs).
