### ISSUE TITLE
No activities during cron

### ISSUE THREAD

**Issue by tassoman** [pa11y/pa11y-dashboard#242]
Hello there, I've upgraded to latest master branch and configured headless chrome to run tasks.
Some tasks are checked correctly, some others are failing because of buggy js inside pages. (#241) 

Cron are run but I can’t get any activity inside the console.
https://gist.github.com/tassoman/55329a4363f84584eab4d34d73220cc0#file-pa11y-logging-L14

**Comment by tassoman** [comment]
> [user@hostname pa11y-dashboard]$ node --version
v12.9.1
>[user@hostname pa11y-dashboard]$ npm --version
6.11.2

**Comment by josebolos** [comment]
Hi @tassoman,

It looks like pa11y crashes when testing `http://culturaestero.regione.emilia-romagna.it/it`. This seems to be an issue with pa11y itself rather than with the dashboard, so I've created https://github.com/pa11y/pa11y/issues/487 in order to track it.

Feel free to subscribe to that issue so will receive notifications when there are any updates posted.

Thanks!

**Comment by josebolos** [comment]
This is now fixed in pa11y 5.3.0.
