### ISSUE TITLE
Ability to group tasks

### ISSUE THREAD

**Issue by perryharlock** [pa11y/pa11y-dashboard#69]

**Comment by nickdunn** [comment]
I would really like to see this feature! 

I'm new to pa11y but am looking at how to set it up in my workplace. We develop and manage dozens of websites, so I can see us wanting one task for each unique template of a site. 

Being able to group the tasks by domain, or group, or project, would mean needing just s single pa11y instance running on our CI box for all projects, instead of s separate dashboard set up for each one.

Given adding the concept of groups could be tricky (CRUD), I wonder if an easier solution would be to group by domain name (inc subdomain).

**Comment by rowanmanning** [comment]
An update on this feature: we won't be adding it to Pa11y Dashboard (very high effort in the current code base), however [Pa11y Sidekick will hopefully have it built in from the start](https://github.com/pa11y/sidekick/issues/10). Thanks for your interest, and please do go and comment on the Sidekick issue if you have input on the way it should work :)
