### ISSUE TITLE
pa11y Tests Not Running

### ISSUE THREAD

**Issue by martincarlin87** [pa11y/pa11y-dashboard#96]
OS name/version - CentOS Linux release 7.2.1511 (Core) 
Node.js version - v4.2.4
pa11y-dashboard version - 1.8.2

Hi,

I had version 1.6.0 installed but just checked my install of the pa11y dashboard after a reboot and noticed that the tests hadn't ran since 30th January.

I tried updating, checking mongo was running and restarting the forever process but I can't seem to fix it or find any errors in the pa11y, nginx or mongo logs, does anyone have any ideas why this is happening?

You can see it here for yourself: http://pa11y.4playtheband.co.uk/

Thanks,
Martin

**Comment by robtarr** [comment]
I just installed the dashboard and am seeing the same problem. I see the tasks in Mongo, but there are no results. Is this a known issue?

pa11y-dashboard - 1.8.2
NodeJS - 4.3.1
MongoDB - 3.0.10

**Comment by rowanmanning** [comment]
Hi @martincarlin87, @robtarr. I'm a little stumped on this at the mo, there have been a few updates to the dashboard since this was posted so maybe as a first step could you update it? Version 1.8.2 wasn't properly tested with Node.js 4.x so it'd be good to move to the latest version :)

If you're still having the issue then I'm happy to help you debug it – you should definitely be seeing some output in the logs if tasks are failing to run. One quick test you could do is running a task manually to see if that works.
